import { createHash } from 'node:crypto';
import type { PrismaClient } from '../prisma.js';
import { Prisma } from '../../generated/prisma/client.js';
import { newId } from '../../lib/ids.js';

export type MemoryKind = 'task' | 'message' | 'action' | 'doc' | 'note' | 'lesson' | 'project_note';
export type MemoryTrust = 'person' | 'derived';

/**
 * A lesson's metadata (spec 2026-09-27 failure lessons §3): the parsed `docs/lessons/*.md` front
 * matter, or the `record_lesson` input, for a `lesson` item's chunk 0. Null for every other kind.
 * Never a place for free text — every value is capped by the writer (tags ≤ 10 × 40 chars, strings
 * ≤ 300) before it lands here.
 */
export interface LessonMeta {
  evidence: 'observed' | 'fixed' | 'confirmed';
  card: string | null;
  pr: string | null;
  tags: string[];
  agent: string | null;
  tab_id: string | null;
  origin: 'file' | 'note';
  path: string | null;
}

/**
 * One chunk of the concierge's searchable memory (spec 2026-09-26 concierge memory §3.1): a card, a
 * message the person typed, a gate decision, a spec/plan section or a note. Decisions answered on a
 * card live in `chat_decisions` (see `ChatDecisionsRepository`), not here. `project_name` is joined in
 * for display; it is null for an account-wide item or an orphaned project.
 */
export interface MemoryItem {
  id: string;
  owner_id: string;
  project_id: string | null;
  project_name: string | null;
  kind: MemoryKind;
  source_id: string;
  chunk_index: number;
  title: string;
  text: string;
  trust: MemoryTrust;
  content_hash: string;
  source_hash: string | null;
  embed_model: string | null;
  meta: LessonMeta | null;
  /** `verified_at != null && verified_hash === content_hash` (spec §3, D8): a changed text drops it. */
  verified: boolean;
  verified_at: string | null;
  source_at: string;
  created_at: string;
  updated_at: string;
}

export interface NewMemoryItem {
  /** Pre-generated by the caller when the row's own id is part of what it stores — a note's `source_id`
   *  is "the note's own id" (spec §3.1), which only a caller minting it up front can guarantee; every
   *  other writer leaves this out and gets a fresh one from here, exactly as before. */
  id?: string;
  owner_id: string;
  project_id: string | null;
  kind: MemoryKind;
  source_id: string;
  chunk_index: number;
  title: string;
  text: string;
  trust: MemoryTrust;
  source_at: Date;
  /** the whole source's hash (a doc file's sha256), so the docs sweeper can skip unchanged files; null otherwise */
  source_hash?: string | null;
  /** Lesson metadata (spec §3); undefined/null for every other kind. `upsertIn` writes it on every
   *  upsert but never touches `verified_*`/`hidden_hash` — those survive a re-index untouched. */
  meta?: LessonMeta | null;
}

export interface MemoryHit extends MemoryItem {
  similarity: number | null;
  rank: number;
}

export interface MemoryFilter {
  ownerId: string;
  projectId?: string;
  kinds?: MemoryKind[];
}

/** Row shape shared by the raw queries below: every `memory_items` column but `embedding` itself
 *  (never selected — it is write-only from here, and never logged), plus the project name join. */
interface RawItem {
  id: string;
  owner_id: string;
  project_id: string | null;
  project_name: string | null;
  kind: string;
  source_id: string;
  chunk_index: number;
  title: string;
  text: string;
  trust: string;
  content_hash: string;
  source_hash: string | null;
  embed_model: string | null;
  meta: LessonMeta | null;
  verified_at: Date | null;
  verified_hash: string | null;
  source_at: Date;
  created_at: Date;
  updated_at: Date;
}

const ITEM_COLUMNS = Prisma.raw(
  `m.id, m.owner_id, m.project_id, m.kind, m.source_id, m.chunk_index, m.title, m.text, m.trust, m.content_hash, m.source_hash, m.embed_model, m.meta, m.verified_at, m.verified_hash, m.source_at, m.created_at, m.updated_at`,
);

/** pgvector's text input format: `[x,y,z]`. Never-finite components (NaN, Infinity) are zeroed rather
 *  than sent malformed, since a bad embedding would otherwise fail the whole write. */
const toVector = (v: number[]): string => `[${v.map((x) => (Number.isFinite(x) ? x : 0)).join(',')}]`;

/** `sha256(title + '\n' + text)`: re-embed only when the chunk's content actually changed. */
const contentHash = (title: string, text: string): string => createHash('sha256').update(`${title}\n${text}`).digest('hex');

const mapRaw = (r: RawItem): MemoryItem => ({
  id: r.id,
  owner_id: r.owner_id,
  project_id: r.project_id,
  project_name: r.project_name,
  kind: r.kind as MemoryKind,
  source_id: r.source_id,
  chunk_index: r.chunk_index,
  title: r.title,
  text: r.text,
  trust: r.trust as MemoryTrust,
  content_hash: r.content_hash,
  source_hash: r.source_hash,
  embed_model: r.embed_model,
  meta: r.meta,
  verified: r.verified_at !== null && r.verified_hash === r.content_hash,
  verified_at: r.verified_at ? r.verified_at.toISOString() : null,
  source_at: r.source_at.toISOString(),
  created_at: r.created_at.toISOString(),
  updated_at: r.updated_at.toISOString(),
});

/** Escapes a person's search text for a LIKE/ILIKE pattern: `%`/`_` are wildcards and `\` is the
 *  escape character itself, so all three must be escaped before wrapping in `%…%`. */
const escapeLike = (s: string): string => s.replace(/[\\%_]/g, (c) => `\\${c}`);

/** Keyset cursor over `(created_at, id)`, newest first: opaque to the caller, defensively decoded — an
 *  old, foreign or tampered cursor is treated as "no cursor" (first page) rather than an error. */
const encodeCursor = (createdAt: Date, id: string): string => Buffer.from(JSON.stringify([createdAt.toISOString(), id])).toString('base64url');
const decodeCursor = (cursor: string): { createdAt: Date; id: string } | null => {
  try {
    const parsed = JSON.parse(Buffer.from(cursor, 'base64url').toString('utf8'));
    if (!Array.isArray(parsed) || parsed.length !== 2 || typeof parsed[0] !== 'string' || typeof parsed[1] !== 'string') return null;
    const createdAt = new Date(parsed[0]);
    if (Number.isNaN(createdAt.getTime())) return null;
    return { createdAt, id: parsed[1] };
  } catch {
    return null;
  }
};

/** What `upsertIn` needs from a client: a plain one or a transaction's. */
type RawClient = Pick<PrismaClient, '$queryRaw'>;

/** `upsertMany`'s body, run inside the caller's transaction (see `upsertMany` for the semantics). */
async function upsertIn(tx: RawClient, items: NewMemoryItem[]): Promise<MemoryItem[]> {
  const out: MemoryItem[] = [];
  for (const it of items) {
    const hash = contentHash(it.title, it.text);
    const meta = it.meta ? JSON.stringify(it.meta) : null;
    const [row] = await tx.$queryRaw<(RawItem & { needs_embedding: boolean })[]>`
      INSERT INTO "memory_items" ("id","owner_id","project_id","kind","source_id","chunk_index","title","text","trust","content_hash","source_hash","meta","source_at","updated_at")
      VALUES (${it.id ?? newId()}, ${it.owner_id}, ${it.project_id}, ${it.kind}, ${it.source_id}, ${it.chunk_index}, ${it.title}, ${it.text}, ${it.trust}, ${hash}, ${it.source_hash ?? null}, ${meta}::jsonb, ${it.source_at}, now())
      ON CONFLICT ("kind","source_id","chunk_index") DO UPDATE SET
        "title" = EXCLUDED."title", "text" = EXCLUDED."text", "trust" = EXCLUDED."trust", "owner_id" = EXCLUDED."owner_id", "project_id" = EXCLUDED."project_id",
        "source_at" = EXCLUDED."source_at", "updated_at" = now(), "content_hash" = EXCLUDED."content_hash", "source_hash" = EXCLUDED."source_hash", "meta" = EXCLUDED."meta",
        "embedding" = CASE WHEN "memory_items"."content_hash" = EXCLUDED."content_hash" THEN "memory_items"."embedding" ELSE NULL END,
        "embed_model" = CASE WHEN "memory_items"."content_hash" = EXCLUDED."content_hash" THEN "memory_items"."embed_model" ELSE NULL END
      RETURNING id, owner_id, project_id, (SELECT name FROM "projects" WHERE id = "project_id") AS project_name,
                kind, source_id, chunk_index, title, text, trust, content_hash, source_hash, embed_model, meta, verified_at, verified_hash, source_at, created_at, updated_at,
                (embedding IS NULL) AS needs_embedding`;
    if (row!.needs_embedding) out.push(mapRaw(row!));
  }
  return out;
}

/**
 * Concierge memory (spec 2026-09-26 concierge memory): free-text chunks from cards, the person's chat
 * messages, gate decisions, project specs/plans and notes, embedded for similarity search alongside
 * full-text (raw SQL throughout — `embedding` is an `Unsupported` Prisma type).
 */
export class MemoryItemsRepository {
  constructor(private db: PrismaClient) {}

  /**
   * Insert or update on `(kind, source_id, chunk_index)`. An unchanged `content_hash` keeps the
   * embedding (the writer re-sent the same text); a changed one clears it, so the sweeper picks the
   * row up again. `owner_id` (fix round 1) always follows the caller's latest write too — a card whose
   * project changed owner must stop showing in the old owner's search on the very next re-index, not
   * once a second, unrelated sweep of the new owner happens to run first. Returns only the rows whose
   * embedding is now null — the ones the sweeper still owes an embedding, never the ones that kept theirs.
   */
  async upsertMany(items: NewMemoryItem[]): Promise<MemoryItem[]> {
    if (items.length === 0) return [];
    return this.db.$transaction((tx) => upsertIn(tx, items));
  }

  /**
   * Replaces every chunk of one source in a single transaction: the chunks from `items.length` on are
   * deleted, then `items` (chunk indexes `0..items.length-1`) are upserted exactly like `upsertMany`.
   * The docs sweeper's re-chunk (spec §4, fix round 1): a separate trim and write could be split by a
   * crash, leaving a stale tail next to a chunk 0 whose new hash says the file is up to date — so it
   * would never be looked at again. Here either both happen or neither does. `items` empty deletes every
   * chunk of the source. Returns the rows that now need an embedding, like `upsertMany`.
   */
  async replaceSourceChunks(kind: MemoryKind, sourceId: string, items: NewMemoryItem[]): Promise<MemoryItem[]> {
    return this.db.$transaction(async (tx) => {
      await tx.$executeRaw`DELETE FROM "memory_items" WHERE "kind" = ${kind} AND "source_id" = ${sourceId} AND "chunk_index" >= ${items.length}`;
      return upsertIn(tx, items);
    });
  }

  /**
   * Deletes every `doc` row whose link id — the `source_id` part before the first `:` — is not in
   * `linkIds` (spec D15, fix round 1): a link that was unlinked, or whose machine was deleted (the link
   * cascades, `memory_items` has no FK to it), would otherwise stay searchable forever, and a re-link
   * (a new link id) would index the same files a second time. **An empty `linkIds` deletes every doc
   * row**: the caller must only pass the result of a link listing that succeeded. Never another kind.
   */
  async deleteDocsNotInLinks(linkIds: string[]): Promise<number> {
    return this.db.$executeRaw`DELETE FROM "memory_items" WHERE "kind" = 'doc' AND split_part("source_id", ':', 1) <> ALL(${linkIds}::text[])`;
  }

  /** Removes chunks `fromIndex..` of a source (a doc re-chunked shorter): never chunk 0.. of a
   *  different source, never a lower chunk index. */
  async deleteChunksFrom(kind: MemoryKind, sourceId: string, fromIndex: number): Promise<number> {
    return this.db.$executeRaw`DELETE FROM "memory_items" WHERE "kind" = ${kind} AND "source_id" = ${sourceId} AND "chunk_index" >= ${fromIndex}`;
  }

  /** Every chunk of these sources (a task/doc/etc. that is gone). */
  async deleteBySource(kind: MemoryKind, sourceIds: string[]): Promise<number> {
    if (sourceIds.length === 0) return 0;
    return this.db.$executeRaw`DELETE FROM "memory_items" WHERE "kind" = ${kind} AND "source_id" IN (${Prisma.join(sourceIds)})`;
  }

  /** `source_id → source_hash` of chunk 0, for sources under this prefix (a project link's `<id>:`),
   *  so a docs sweep can skip a file whose hash did not change. Only rows with a non-null hash. */
  async listSourceHashes(kind: MemoryKind, sourceIdPrefix: string): Promise<Map<string, string>> {
    const like = `${escapeLike(sourceIdPrefix)}%`;
    const rows = await this.db.$queryRaw<{ source_id: string; source_hash: string }[]>`
      SELECT "source_id", "source_hash" FROM "memory_items"
      WHERE "kind" = ${kind} AND "chunk_index" = 0 AND "source_hash" IS NOT NULL AND "source_id" LIKE ${like} ESCAPE '\\'`;
    return new Map(rows.map((r) => [r.source_id, r.source_hash]));
  }

  /** `source_id → source_at`, for the card sweeper: only re-chunk a task whose `updated_at` is newer. */
  async listSourceAt(kind: 'task', ownerId: string): Promise<Map<string, string>> {
    const rows = await this.db.$queryRaw<{ source_id: string; source_at: Date }[]>`
      SELECT "source_id", "source_at" FROM "memory_items" WHERE "kind" = ${kind} AND "owner_id" = ${ownerId}`;
    return new Map(rows.map((r) => [r.source_id, r.source_at.toISOString()]));
  }

  async setEmbedding(id: string, vector: number[], model: string): Promise<void> {
    const v = toVector(vector);
    await this.db.$executeRaw`UPDATE "memory_items" SET "embedding" = ${v}::vector, "embed_model" = ${model} WHERE "id" = ${id}`;
  }

  /** Not yet embedded (the sweeper's backlog), oldest first. */
  async listToEmbed(limit: number): Promise<Pick<MemoryItem, 'id' | 'title' | 'text'>[]> {
    return this.db.$queryRaw<{ id: string; title: string; text: string }[]>`
      SELECT "id", "title", "text" FROM "memory_items" WHERE "embedding" IS NULL ORDER BY "created_at" ASC LIMIT ${limit}`;
  }

  /**
   * The `k` nearest items of this owner, best (highest cosine similarity) first: an exact scan, no ANN
   * index (spec D5) — never another owner's rows, never an unembedded row, `projectId`/`kinds` narrow
   * further when given. `rank` is the 1-based position in this result.
   */
  async nearest(filter: MemoryFilter, vector: number[], k: number): Promise<MemoryHit[]> {
    const v = toVector(vector);
    const rows = await this.db.$queryRaw<(RawItem & { similarity: number | string })[]>`
      SELECT ${ITEM_COLUMNS}, p.name AS project_name,
             1 - (m.embedding <=> ${v}::vector) AS similarity
      FROM "memory_items" m LEFT JOIN "projects" p ON p.id = m.project_id
      WHERE m.owner_id = ${filter.ownerId} AND m.embedding IS NOT NULL
        AND (m.hidden_hash IS NULL OR m.hidden_hash <> m.content_hash)
        AND (${filter.projectId ?? null}::text IS NULL OR m.project_id = ${filter.projectId ?? null})
        AND (${filter.kinds ?? null}::text[] IS NULL OR m.kind = ANY(${filter.kinds ?? null}::text[]))
      ORDER BY m.embedding <=> ${v}::vector
      LIMIT ${k}`;
    return rows.map((r, i) => ({ ...mapRaw(r), similarity: Number(r.similarity), rank: i + 1 }));
  }

  /** Postgres full-text over `title || ' ' || text` (D5: no tsvector index, one owner's rows are few),
   *  best `ts_rank` first. A query with no lexeme (only punctuation) matches nothing rather than
   *  throwing or matching everything — `numnode(tsq) > 0` guards it. */
  async textSearch(filter: MemoryFilter, query: string, k: number): Promise<MemoryHit[]> {
    const rows = await this.db.$queryRaw<RawItem[]>`
      WITH q AS (SELECT websearch_to_tsquery('simple', ${query}) AS tsq)
      SELECT ${ITEM_COLUMNS}, p.name AS project_name
      FROM "memory_items" m CROSS JOIN q LEFT JOIN "projects" p ON p.id = m.project_id
      WHERE m.owner_id = ${filter.ownerId}
        AND (m.hidden_hash IS NULL OR m.hidden_hash <> m.content_hash)
        AND (${filter.projectId ?? null}::text IS NULL OR m.project_id = ${filter.projectId ?? null})
        AND (${filter.kinds ?? null}::text[] IS NULL OR m.kind = ANY(${filter.kinds ?? null}::text[]))
        AND numnode(q.tsq) > 0
        AND to_tsvector('simple', m.title || ' ' || m.text) @@ q.tsq
      ORDER BY ts_rank(to_tsvector('simple', m.title || ' ' || m.text), q.tsq) DESC, m.source_at DESC
      LIMIT ${k}`;
    return rows.map((r, i) => ({ ...mapRaw(r), similarity: null, rank: i + 1 }));
  }

  async findManyForOwner(ids: string[], ownerId: string): Promise<MemoryItem[]> {
    if (ids.length === 0) return [];
    const rows = await this.db.$queryRaw<RawItem[]>`
      SELECT ${ITEM_COLUMNS}, p.name AS project_name
      FROM "memory_items" m LEFT JOIN "projects" p ON p.id = m.project_id
      WHERE m.owner_id = ${ownerId} AND m.id IN (${Prisma.join(ids)})
        AND (m.hidden_hash IS NULL OR m.hidden_hash <> m.content_hash)`;
    return rows.map(mapRaw);
  }

  countNotesSince(ownerId: string, since: Date): Promise<number> {
    return this.db.memoryItem.count({ where: { ownerId, kind: 'note', createdAt: { gte: since } } });
  }

  /** "Anotações do concierge" (spec D12): newest first, keyset cursor over `(created_at, id)`. */
  async listNotes(ownerId: string, opts: { cursor?: string; limit: number }): Promise<{ items: MemoryItem[]; next_cursor: string | null }> {
    const cur = opts.cursor ? decodeCursor(opts.cursor) : null;
    const rows = await this.db.$queryRaw<RawItem[]>`
      SELECT ${ITEM_COLUMNS}, p.name AS project_name
      FROM "memory_items" m LEFT JOIN "projects" p ON p.id = m.project_id
      WHERE m.owner_id = ${ownerId} AND m.kind = 'note'
        AND (${cur === null}::boolean OR (m.created_at, m.id) < (${cur?.createdAt ?? new Date(0)}, ${cur?.id ?? ''}))
      ORDER BY m.created_at DESC, m.id DESC
      LIMIT ${opts.limit + 1}`;
    const hasMore = rows.length > opts.limit;
    const page = rows.slice(0, opts.limit);
    const last = page[page.length - 1];
    const next_cursor = hasMore && last ? encodeCursor(last.created_at, last.id) : null;
    return { items: page.map(mapRaw), next_cursor };
  }

  /** "Esquecer": only the owner's own note, never a card/message/action/doc chunk. */
  async deleteNote(id: string, ownerId: string): Promise<boolean> {
    const { count } = await this.db.memoryItem.deleteMany({ where: { id, ownerId, kind: 'note' } });
    return count > 0;
  }

  /**
   * "Verificar" (spec §3, D8): stamps who and the current `content_hash`. Only this owner's `lesson`
   * chunk 0 — never another owner's row, never a non-lesson row (verification only ever means anything
   * for a lesson). False, nothing changed, when the id/owner/kind don't match.
   */
  async setVerified(id: string, ownerId: string, byUserId: string): Promise<boolean> {
    const count = await this.db.$executeRaw`
      UPDATE "memory_items" SET "verified_at" = now(), "verified_by" = ${byUserId}, "verified_hash" = "content_hash"
      WHERE "id" = ${id} AND "owner_id" = ${ownerId} AND "kind" = 'lesson' AND "chunk_index" = 0`;
    return count > 0;
  }

  /** "Desfazer verificação": the inverse of `setVerified`, same scope. */
  async clearVerified(id: string, ownerId: string): Promise<boolean> {
    const count = await this.db.$executeRaw`
      UPDATE "memory_items" SET "verified_at" = NULL, "verified_by" = NULL, "verified_hash" = NULL
      WHERE "id" = ${id} AND "owner_id" = ${ownerId} AND "kind" = 'lesson' AND "chunk_index" = 0`;
    return count > 0;
  }

  /**
   * "Esquecer" a file lesson (spec §6): sets `hidden_hash` = `content_hash` on every chunk of the
   * item's source (its `(kind, source_id)`), so `nearest`/`textSearch`/`listLessons`/`findManyForOwner`
   * skip it. Survives a re-index with the same content (the upsert never touches `hidden_hash`); a
   * changed content (new `content_hash`) no longer matches the stored `hidden_hash` and comes back as
   * a fresh, unverified lesson. False when `id` is not this owner's row.
   */
  async hideSource(id: string, ownerId: string): Promise<boolean> {
    const count = await this.db.$executeRaw`
      UPDATE "memory_items" m SET "hidden_hash" = m."content_hash"
      FROM (SELECT "kind", "source_id" FROM "memory_items" WHERE "id" = ${id} AND "owner_id" = ${ownerId}) t
      WHERE m."owner_id" = ${ownerId} AND m."kind" = t."kind" AND m."source_id" = t."source_id"`;
    return count > 0;
  }

  /**
   * "Lições" list (spec §6): the owner's `lesson` items, one row per source (chunk 0), never a hidden
   * one, newest `source_at` first — `q` matches title or text (ILIKE), `projectId` narrows further.
   * Keyset cursor over `(source_at, id)`.
   */
  async listLessons(ownerId: string, o: { q?: string; projectId?: string; cursor?: string; limit: number }): Promise<{ items: MemoryItem[]; next_cursor: string | null }> {
    const cur = o.cursor ? decodeCursor(o.cursor) : null;
    const like = o.q !== undefined ? `%${escapeLike(o.q)}%` : null;
    const rows = await this.db.$queryRaw<RawItem[]>`
      SELECT ${ITEM_COLUMNS}, p.name AS project_name
      FROM "memory_items" m LEFT JOIN "projects" p ON p.id = m.project_id
      WHERE m.owner_id = ${ownerId} AND m.kind = 'lesson' AND m.chunk_index = 0
        AND (m.hidden_hash IS NULL OR m.hidden_hash <> m.content_hash)
        AND (${o.projectId ?? null}::text IS NULL OR m.project_id = ${o.projectId ?? null})
        AND (${like}::text IS NULL OR m.title ILIKE ${like} ESCAPE '\\' OR m.text ILIKE ${like} ESCAPE '\\')
        AND (${cur === null}::boolean OR (m.source_at, m.id) < (${cur?.createdAt ?? new Date(0)}, ${cur?.id ?? ''}))
      ORDER BY m.source_at DESC, m.id DESC
      LIMIT ${o.limit + 1}`;
    const hasMore = rows.length > o.limit;
    const page = rows.slice(0, o.limit);
    const last = page[page.length - 1];
    const next_cursor = hasMore && last ? encodeCursor(last.source_at, last.id) : null;
    return { items: page.map(mapRaw), next_cursor };
  }

  /** One lesson, "Abrir origem"/verify-route lookups: this owner's `lesson` chunk 0, never a hidden one. */
  async findLessonForOwner(id: string, ownerId: string): Promise<MemoryItem | null> {
    const rows = await this.db.$queryRaw<RawItem[]>`
      SELECT ${ITEM_COLUMNS}, p.name AS project_name
      FROM "memory_items" m LEFT JOIN "projects" p ON p.id = m.project_id
      WHERE m.id = ${id} AND m.owner_id = ${ownerId} AND m.kind = 'lesson' AND m.chunk_index = 0
        AND (m.hidden_hash IS NULL OR m.hidden_hash <> m.content_hash)`;
    return rows[0] ? mapRaw(rows[0]) : null;
  }

  /** `project_id → source_at` of the newest chunk (spec §4, D6): the note indexer's "is this project's
   *  note stale" check, mirroring `listSourceAt` but grouped since a note's sections span many chunks. */
  async latestSourceAt(kind: 'project_note', ownerId: string): Promise<Map<string, string>> {
    const rows = await this.db.$queryRaw<{ project_id: string; source_at: Date }[]>`
      SELECT "project_id", MAX("source_at") AS source_at FROM "memory_items"
      WHERE "kind" = ${kind} AND "owner_id" = ${ownerId} AND "project_id" IS NOT NULL
      GROUP BY "project_id"`;
    return new Map(rows.map((r) => [r.project_id, r.source_at.toISOString()]));
  }

  /** `record_lesson`'s hourly cap (spec D10): this owner's note-origin lessons (chunk 0) created since `since`. */
  async countNoteLessonsSince(ownerId: string, since: Date): Promise<number> {
    const rows = await this.db.$queryRaw<{ count: bigint }[]>`
      SELECT COUNT(*) AS count FROM "memory_items"
      WHERE "owner_id" = ${ownerId} AND "kind" = 'lesson' AND "chunk_index" = 0
        AND "meta"->>'origin' = 'note' AND "created_at" >= ${since}`;
    return Number(rows[0]!.count);
  }
}
