import type { ReactNode } from 'react';
import { useLang, type Dict } from '../i18n';
import { Chevron, Site, SiteFooter, SiteHeader, trackCta } from '../Site';
import { useReveal } from '../useReveal';

/**
 * /brand/ — the logo, mark, colors and typography for anyone writing about
 * termhub. The files come from public/brand/, generated by brand/build.sh.
 */

const KIT = '/brand';
const ZIP = `${KIT}/termhub-brand.zip`;

type File = { label: string; href: string };

function Downloads({ files }: { files: File[] }) {
  return (
    <ul className="mt-4 flex flex-wrap gap-2">
      {files.map((f) => (
        <li key={f.href}>
          <a href={f.href} download className="btn-ghost px-3 py-1 font-mono text-caption">
            {f.label}
          </a>
        </li>
      ))}
    </ul>
  );
}

/** A preview tile; `light` renders the light-background variant on white. */
function Preview({ src, alt, light = false, caption }: { src: string; alt: string; light?: boolean; caption?: string }) {
  return (
    <figure>
      <div className={`flex items-center justify-center rounded-card border border-border-2 p-8 ${light ? 'bg-white' : 'bg-canvas'}`}>
        <img src={src} alt={alt} className="max-h-40 w-auto" />
      </div>
      {caption && <figcaption className="mt-2 text-caption text-muted">{caption}</figcaption>}
    </figure>
  );
}

function Section({ id, title, text, children }: { id: string; title: string; text: string; children: ReactNode }) {
  const ref = useReveal<HTMLElement>();
  return (
    <section id={id} ref={ref} className="reveal border-t border-border-2 py-14">
      <div className="grid gap-8 md:grid-cols-[minmax(0,1fr)_minmax(0,2fr)]">
        <div>
          <h2 className="text-heading-sm">{title}</h2>
          <p className="mt-2 text-body-sm text-frost">{text}</p>
        </div>
        <div>{children}</div>
      </div>
    </section>
  );
}

/** Swatch background for a palette entry; the gradient entry is written as "a → b". */
const swatchStyle = (value: string) => {
  const [a, b] = value.split(' → ');
  return { background: b ? `linear-gradient(135deg, ${a}, ${b})` : a };
};

function Page() {
  const { t } = useLang();
  const b = t.brand;
  return (
    <div className="min-h-full">
      <SiteHeader
        nav={
          <a href="/" className="nav-link">
            ‹ {b.back}
          </a>
        }
      />

      <main className="mx-auto max-w-page px-4 md:px-6">
        <section className="pb-14 pt-14 md:pt-20">
          <h1 className="text-heading-lg md:text-display">{b.title}</h1>
          <p className="mt-5 max-w-2xl text-subheading text-frost">{b.lead}</p>
          <div className="mt-7 flex flex-wrap items-center gap-3">
            <a href={ZIP} download className="btn-primary" onClick={trackCta('brand_zip', 'hero')}>
              {b.download_all} <Chevron />
            </a>
            <span className="text-caption text-muted">{b.download_hint}</span>
          </div>
        </section>

        <Section id="simbolo" title={b.mark.title} text={b.mark.text}>
          <div className="grid gap-4 sm:grid-cols-2">
            <Preview src="/favicon.svg" alt="termhub" caption={b.logo.on_dark} />
            <Preview src="/favicon.svg" alt="termhub" light caption={b.logo.on_light} />
          </div>
          <Downloads
            files={[
              { label: `${b.files.svg}`, href: `${KIT}/termhub-mark.svg` },
              { label: `${b.files.png} 1024`, href: `${KIT}/termhub-mark-1024.png` },
              { label: `${b.files.png} 512`, href: `${KIT}/termhub-mark-512.png` },
              { label: `${b.files.png} 180`, href: `${KIT}/termhub-mark-180.png` },
              { label: `${b.files.png} 96`, href: `${KIT}/termhub-mark-96.png` },
            ]}
          />
        </Section>

        <Section id="logotipo" title={b.logo.title} text={b.logo.text}>
          <div className="grid gap-4">
            <Preview src="/logo.svg" alt="termhub" caption={b.logo.on_dark} />
            <Preview src={`${KIT}/termhub-logo-on-light.svg`} alt="termhub" light caption={b.logo.on_light} />
          </div>
          <Downloads
            files={[
              { label: `${b.files.svg} · ${b.logo.on_dark}`, href: `${KIT}/termhub-logo.svg` },
              { label: `${b.files.png} · ${b.logo.on_dark}`, href: `${KIT}/termhub-logo.png` },
              { label: `${b.files.svg} · ${b.logo.on_light}`, href: `${KIT}/termhub-logo-on-light.svg` },
              { label: `${b.files.png} · ${b.logo.on_light}`, href: `${KIT}/termhub-logo-on-light.png` },
            ]}
          />
        </Section>

        <Section id="social" title={b.social.title} text={b.social.text}>
          <div className="grid gap-4 sm:grid-cols-3">
            {b.social.items.map((item) => (
              <figure key={item.file}>
                <a href={`${KIT}/${item.file}`} download className="block overflow-hidden rounded-card border border-border-2 transition duration-150 hover:border-border/40">
                  <img src={`${KIT}/${item.file}`} alt={item.label} className="aspect-[4/3] w-full object-cover" loading="lazy" />
                </a>
                <figcaption className="mt-2 text-caption text-muted">{item.label}</figcaption>
              </figure>
            ))}
          </div>
        </Section>

        <Section id="cores" title={b.colors.title} text={b.colors.text}>
          <ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {b.colors.items.map((c) => (
              <li key={c.name} className="rounded-card border border-border-2 bg-surface p-3">
                <div className="h-16 rounded-field border border-border-2" style={swatchStyle(c.value)} />
                <p className="mt-3 text-body-sm text-white">{c.name}</p>
                <p className="font-mono text-caption text-accent">{c.value}</p>
                <p className="mt-1 text-caption text-muted">{c.role}</p>
              </li>
            ))}
          </ul>
        </Section>

        <Section id="tipografia" title={b.type.title} text={b.type.text}>
          <ul className="grid gap-4">
            {b.type.items.map((f) => (
              <li key={f.name} className="rounded-card border border-border-2 bg-surface p-5">
                <p className={`text-heading-sm text-white ${f.mono ? 'font-mono' : ''}`}>{f.sample}</p>
                <p className="mt-3 text-body-sm text-frost">
                  <span className="text-white">{f.name}</span> · {f.role}
                </p>
              </li>
            ))}
          </ul>
        </Section>

        <Section id="uso" title={b.rules.title} text="">
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="rounded-card border border-border-2 bg-surface p-5">
              <h3 className="text-body text-accent">{b.rules.dos_title}</h3>
              <ul className="mt-3 space-y-2 text-body-sm text-frost">
                {b.rules.dos.map((r) => (
                  <li key={r} className="flex gap-2">
                    <span aria-hidden="true">✓</span> {r}
                  </li>
                ))}
              </ul>
            </div>
            <div className="rounded-card border border-border-2 bg-surface p-5">
              <h3 className="text-body text-muted">{b.rules.donts_title}</h3>
              <ul className="mt-3 space-y-2 text-body-sm text-frost">
                {b.rules.donts.map((r) => (
                  <li key={r} className="flex gap-2">
                    <span aria-hidden="true">✕</span> {r}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </Section>

        <section className="border-t border-border-2 py-14">
          <a href={ZIP} download className="btn-primary" onClick={trackCta('brand_zip', 'footer')}>
            {b.download_all} <Chevron />
          </a>
        </section>
      </main>

      <SiteFooter />
    </div>
  );
}

const meta = (t: Dict) => t.brand.meta;

export function BrandPage() {
  return (
    <Site meta={meta}>
      <Page />
    </Site>
  );
}
